service: serverless-reminders # NOTE: update this with your service name
#app: your-app-name
#tenant: your-tenant-name

provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:*"
      Resource:
        - "*"
functions:
  dailyReminder:
    handler: handler.sendReminderDaily
    events:
      - schedule: rate(1 day)
  weekendReminder:
    handler: handler.sendReminderWeekend
    events:
#       - schedule: cron(30 22 ? * SUN,SAT *)

# service: serverless-node-cron

# provider:
#   name: aws
#   runtime: nodejs8.10
#   iamRoleStatements:
#     -  Effect: "Allow"
#        Action:
#          - "ses:*"
#        Resource:
#          - "*"
# functions:
#   dailyReminder:
#     handler: handler.sendReminderDaily
#     events:
#       # Invoke the Lambda function everyday
#       - schedule: rate(1 day)
#   weekendReminder:
#     handler: handler.sendReminderWeekend
#     events:
#       # Invoke the Lambda function every weekend at 1pm US/Eastern Time
#       - schedule: cron(30 22 ? * SUN,SAT *)